import type { SqliteSink, TrustScoreRecord, BadgeRecord, WarningRecord, PriceAccuracyStats, UptimeStats, ReviewStats } from '../sinks/SqliteSink.js';
import { logger } from '../utils/logger.js';
import config from '../../config/crawler.config.js';

// Trust score weight configuration
const TRUST_WEIGHTS = {
  priceAccuracy: 0.35,   // Most important - 35%
  uptime: 0.25,          // 25%
  reviews: 0.20,         // 20%
  freshness: 0.20,       // 20%
};

// Score thresholds
const SCORE_THRESHOLDS = {
  excellent: 85,
  good: 70,
  fair: 50,
  // Below 50 = poor
};

// Badge definitions
const BADGE_DEFINITIONS: Record<string, Omit<BadgeRecord, 'id' | 'providerId' | 'awardedAt' | 'expiresAt' | 'autoGenerated'>> = {
  verified: {
    badgeType: 'verified',
    badgeLabel: 'Verified Provider',
    badgeLabelFa: 'ارائه‌دهنده تایید شده',
    description: 'This provider has been manually verified',
    descriptionFa: 'این ارائه‌دهنده به صورت دستی تأیید شده است',
  },
  best_accuracy: {
    badgeType: 'best_accuracy',
    badgeLabel: 'Best Accuracy',
    badgeLabelFa: 'دقیق‌ترین قیمت',
    description: 'Top 3 in price accuracy',
    descriptionFa: 'جزو ۳ ارائه‌دهنده برتر در دقت قیمت',
  },
  fast_updates: {
    badgeType: 'fast_updates',
    badgeLabel: 'Fast Updates',
    badgeLabelFa: 'به‌روزرسانی سریع',
    description: 'Average update time under 20 seconds',
    descriptionFa: 'میانگین زمان به‌روزرسانی کمتر از ۲۰ ثانیه',
  },
  high_rated: {
    badgeType: 'high_rated',
    badgeLabel: 'Highly Rated',
    badgeLabelFa: 'امتیاز بالا',
    description: '4.5+ average rating from users',
    descriptionFa: 'میانگین امتیاز ۴.۵ یا بالاتر از کاربران',
  },
  reliable: {
    badgeType: 'reliable',
    badgeLabel: 'Reliable',
    badgeLabelFa: 'قابل اعتماد',
    description: '99%+ uptime in the last 30 days',
    descriptionFa: 'بیش از ۹۹٪ آپتایم در ۳۰ روز گذشته',
  },
  best_spread: {
    badgeType: 'best_spread',
    badgeLabel: 'Best Spread',
    badgeLabelFa: 'کمترین اختلاف قیمت',
    description: 'Lowest buy/sell price spread',
    descriptionFa: 'کمترین اختلاف بین قیمت خرید و فروش',
  },
};

export type TrustTier = 'excellent' | 'good' | 'fair' | 'poor';

export interface ProviderTrustScore {
  providerId: string;
  providerName: string;
  overallScore: number;
  tier: TrustTier;
  breakdown: {
    priceAccuracy: { score: number; details: string };
    uptime: { score: number; details: string };
    reviews: { score: number; details: string };
    freshness: { score: number; details: string };
  };
  badges: BadgeRecord[];
  warnings: WarningRecord[];
  trend: 'improving' | 'stable' | 'declining';
  lastUpdated: Date;
}

export interface TrustScoreSummary {
  providers: ProviderTrustScore[];
  totalProviders: number;
  avgScore: number;
  lastCalculated: Date;
}

export class TrustScoreService {
  private dbSink: SqliteSink | null = null;
  private providerNames: Map<string, string> = new Map();
  private lastFetchTimes: Map<string, Date> = new Map();
  private responseTimesMs: Map<string, number[]> = new Map(); // Track response times for fast_updates badge
  private priceSpreadData: Map<string, number[]> = new Map(); // Track spreads for best_spread badge

  /**
   * Initialize with database sink
   */
  initialize(dbSink: SqliteSink): void {
    this.dbSink = dbSink;

    // Initialize provider names from config
    for (const [id, providerConfig] of Object.entries(config.providers)) {
      this.providerNames.set(id, providerConfig.name);
    }

    logger.info('TrustScoreService initialized');
  }

  /**
   * Update last fetch time for a provider (used for freshness calculation)
   */
  updateLastFetchTime(providerId: string): void {
    this.lastFetchTimes.set(providerId, new Date());
  }

  /**
   * Track response time for a provider (used for fast_updates badge)
   */
  trackResponseTime(providerId: string, responseTimeMs: number): void {
    const times = this.responseTimesMs.get(providerId) ?? [];
    times.push(responseTimeMs);
    // Keep last 100 samples
    if (times.length > 100) {
      times.shift();
    }
    this.responseTimesMs.set(providerId, times);
  }

  /**
   * Track price spread for a provider (used for best_spread badge)
   */
  trackPriceSpread(providerId: string, buyPrice: number, sellPrice: number): void {
    if (buyPrice <= 0 || sellPrice <= 0) return;
    const spreadPercent = Math.abs((buyPrice - sellPrice) / ((buyPrice + sellPrice) / 2)) * 100;
    const spreads = this.priceSpreadData.get(providerId) ?? [];
    spreads.push(spreadPercent);
    // Keep last 100 samples
    if (spreads.length > 100) {
      spreads.shift();
    }
    this.priceSpreadData.set(providerId, spreads);
  }

  /**
   * Get average response time for a provider
   */
  getAverageResponseTime(providerId: string): number | null {
    const times = this.responseTimesMs.get(providerId);
    if (!times || times.length < 5) return null;
    return times.reduce((sum, t) => sum + t, 0) / times.length;
  }

  /**
   * Get average spread for a provider
   */
  getAverageSpread(providerId: string): number | null {
    const spreads = this.priceSpreadData.get(providerId);
    if (!spreads || spreads.length < 5) return null;
    return spreads.reduce((sum, s) => sum + s, 0) / spreads.length;
  }

  /**
   * Get tier from score
   */
  private getTier(score: number): TrustTier {
    if (score >= SCORE_THRESHOLDS.excellent) return 'excellent';
    if (score >= SCORE_THRESHOLDS.good) return 'good';
    if (score >= SCORE_THRESHOLDS.fair) return 'fair';
    return 'poor';
  }

  /**
   * Calculate price accuracy score (0-100)
   * Lower deviation = higher score
   */
  private calculatePriceAccuracyScore(providerId: string): { score: number; details: string } {
    if (!this.dbSink) {
      return { score: 50, details: 'No data available' };
    }

    const stats = this.dbSink.getPriceAccuracyStats(providerId, 7);
    if (!stats || stats.sampleCount < 10) {
      return { score: 50, details: 'Insufficient data' };
    }

    // Score calculation: 100 - (avgAbsDeviation * 10)
    // 0% deviation = 100, 2% deviation = 80, 5% deviation = 50, 10%+ = 0
    const score = Math.max(0, Math.min(100, 100 - (stats.avgAbsDeviation * 10)));
    const details = `${stats.avgAbsDeviation.toFixed(1)}% avg deviation from market (${stats.sampleCount} samples)`;

    return { score: Math.round(score), details };
  }

  /**
   * Calculate uptime score (0-100)
   */
  private calculateUptimeScore(providerId: string): { score: number; details: string } {
    if (!this.dbSink) {
      return { score: 50, details: 'No data available' };
    }

    const stats = this.dbSink.getUptimeStats(providerId, 30);
    if (!stats || stats.totalChecks < 10) {
      return { score: 50, details: 'Insufficient data' };
    }

    const score = stats.uptimePercent;
    const details = `${stats.uptimePercent.toFixed(1)}% uptime (${stats.totalChecks} checks)`;

    return { score: Math.round(score), details };
  }

  /**
   * Calculate review score (0-100)
   */
  private calculateReviewScore(providerId: string): { score: number; details: string } {
    if (!this.dbSink) {
      return { score: 50, details: 'No reviews yet' };
    }

    const stats = this.dbSink.getReviewStats(providerId);
    if (!stats || stats.totalReviews < 3) {
      return { score: 50, details: 'Not enough reviews' };
    }

    // Convert 1-5 rating to 0-100 score
    const score = ((stats.avgRating - 1) / 4) * 100;
    const details = `${stats.avgRating.toFixed(1)}/5 from ${stats.totalReviews} reviews`;

    return { score: Math.round(score), details };
  }

  /**
   * Calculate freshness score (0-100)
   * Based on how recently prices were updated
   */
  private calculateFreshnessScore(providerId: string): { score: number; details: string } {
    const lastFetch = this.lastFetchTimes.get(providerId);
    if (!lastFetch) {
      return { score: 50, details: 'No recent data' };
    }

    const ageMs = Date.now() - lastFetch.getTime();
    const ageSeconds = ageMs / 1000;

    // Score: 100 at 0s, linearly decreasing to 0 at 5 minutes
    const maxAgeSeconds = 300; // 5 minutes
    const score = Math.max(0, 100 - ((ageSeconds / maxAgeSeconds) * 100));

    let details: string;
    if (ageSeconds < 60) {
      details = `Updated ${Math.round(ageSeconds)}s ago`;
    } else {
      details = `Updated ${Math.round(ageSeconds / 60)}m ago`;
    }

    return { score: Math.round(score), details };
  }

  /**
   * Calculate trend based on score history
   */
  private calculateTrend(providerId: string): 'improving' | 'stable' | 'declining' {
    if (!this.dbSink) return 'stable';

    const history = this.dbSink.getTrustScoreHistory(providerId, 7); // Last 7 days
    if (history.length < 3) return 'stable';

    // Compare average of recent scores vs older scores
    const midPoint = Math.floor(history.length / 2);
    const recentScores = history.slice(midPoint);
    const olderScores = history.slice(0, midPoint);

    const recentAvg = recentScores.reduce((sum, s) => sum + s.overallScore, 0) / recentScores.length;
    const olderAvg = olderScores.reduce((sum, s) => sum + s.overallScore, 0) / olderScores.length;

    const diff = recentAvg - olderAvg;

    // Threshold of 3 points for trend change
    if (diff > 3) return 'improving';
    if (diff < -3) return 'declining';
    return 'stable';
  }

  /**
   * Evaluate and update badges for a provider
   */
  evaluateBadges(providerId: string, scores: {
    priceAccuracy: number;
    uptime: number;
    reviews: number;
  }): void {
    if (!this.dbSink) return;

    const now = new Date().toISOString();

    // Best Accuracy badge (score >= 90)
    if (scores.priceAccuracy >= 90) {
      this.dbSink.saveBadge({
        id: `badge_${providerId}_best_accuracy`,
        providerId,
        ...BADGE_DEFINITIONS['best_accuracy'],
        awardedAt: now,
        autoGenerated: true,
      });
    } else {
      this.dbSink.removeBadge(providerId, 'best_accuracy');
    }

    // Reliable badge (uptime >= 99)
    if (scores.uptime >= 99) {
      this.dbSink.saveBadge({
        id: `badge_${providerId}_reliable`,
        providerId,
        ...BADGE_DEFINITIONS['reliable'],
        awardedAt: now,
        autoGenerated: true,
      });
    } else {
      this.dbSink.removeBadge(providerId, 'reliable');
    }

    // High Rated badge (reviews >= 90, which is 4.6+ stars)
    if (scores.reviews >= 90) {
      this.dbSink.saveBadge({
        id: `badge_${providerId}_high_rated`,
        providerId,
        ...BADGE_DEFINITIONS['high_rated'],
        awardedAt: now,
        autoGenerated: true,
      });
    } else {
      this.dbSink.removeBadge(providerId, 'high_rated');
    }

    // Fast Updates badge (average response time < 2000ms = 2 seconds)
    const avgResponseTime = this.getAverageResponseTime(providerId);
    if (avgResponseTime !== null && avgResponseTime < 2000) {
      this.dbSink.saveBadge({
        id: `badge_${providerId}_fast_updates`,
        providerId,
        ...BADGE_DEFINITIONS['fast_updates'],
        awardedAt: now,
        autoGenerated: true,
      });
    } else {
      this.dbSink.removeBadge(providerId, 'fast_updates');
    }

    // Best Spread badge (average spread < 0.5%)
    const avgSpread = this.getAverageSpread(providerId);
    if (avgSpread !== null && avgSpread < 0.5) {
      this.dbSink.saveBadge({
        id: `badge_${providerId}_best_spread`,
        providerId,
        ...BADGE_DEFINITIONS['best_spread'],
        awardedAt: now,
        autoGenerated: true,
      });
    } else {
      this.dbSink.removeBadge(providerId, 'best_spread');
    }
  }

  /**
   * Evaluate badges for all providers (called during bulk calculation)
   * Awards badges to top performers in each category
   */
  evaluateCompetitiveBadges(allScores: ProviderTrustScore[]): void {
    if (!this.dbSink || allScores.length < 3) return;

    const now = new Date().toISOString();

    // Sort by price accuracy and award to top 3
    const byAccuracy = [...allScores]
      .filter(s => s.breakdown.priceAccuracy.score > 50)
      .sort((a, b) => b.breakdown.priceAccuracy.score - a.breakdown.priceAccuracy.score)
      .slice(0, 3);

    for (const score of byAccuracy) {
      this.dbSink.saveBadge({
        id: `badge_${score.providerId}_best_accuracy`,
        providerId: score.providerId,
        ...BADGE_DEFINITIONS['best_accuracy'],
        awardedAt: now,
        autoGenerated: true,
      });
    }

    // Remove badge from providers not in top 3
    for (const score of allScores) {
      if (!byAccuracy.find(s => s.providerId === score.providerId)) {
        this.dbSink.removeBadge(score.providerId, 'best_accuracy');
      }
    }
  }

  /**
   * Calculate trust score for a single provider
   */
  calculateProviderScore(providerId: string): ProviderTrustScore {
    const priceAccuracy = this.calculatePriceAccuracyScore(providerId);
    const uptime = this.calculateUptimeScore(providerId);
    const reviews = this.calculateReviewScore(providerId);
    const freshness = this.calculateFreshnessScore(providerId);

    // Calculate weighted overall score
    const overallScore =
      (priceAccuracy.score * TRUST_WEIGHTS.priceAccuracy) +
      (uptime.score * TRUST_WEIGHTS.uptime) +
      (reviews.score * TRUST_WEIGHTS.reviews) +
      (freshness.score * TRUST_WEIGHTS.freshness);

    const tier = this.getTier(overallScore);
    const trend = this.calculateTrend(providerId);

    // Evaluate badges based on scores
    this.evaluateBadges(providerId, {
      priceAccuracy: priceAccuracy.score,
      uptime: uptime.score,
      reviews: reviews.score,
    });

    // Get badges and warnings from DB
    const badges = this.dbSink?.getProviderBadges(providerId) ?? [];
    const warnings = this.dbSink?.getActiveWarnings(providerId) ?? [];

    const result: ProviderTrustScore = {
      providerId,
      providerName: this.providerNames.get(providerId) ?? providerId,
      overallScore: Math.round(overallScore * 10) / 10,
      tier,
      breakdown: {
        priceAccuracy,
        uptime,
        reviews,
        freshness,
      },
      badges,
      warnings,
      trend,
      lastUpdated: new Date(),
    };

    // Save to database
    if (this.dbSink) {
      const scoreRecord: TrustScoreRecord = {
        id: `trust_${providerId}_${Date.now()}`,
        providerId,
        overallScore: result.overallScore,
        priceAccuracyScore: priceAccuracy.score,
        uptimeScore: uptime.score,
        reviewScore: reviews.score,
        freshnessScore: freshness.score,
        calculatedAt: new Date().toISOString(),
        factorsJson: JSON.stringify(result.breakdown),
      };
      this.dbSink.saveTrustScore(scoreRecord);
    }

    return result;
  }

  /**
   * Calculate trust scores for all providers
   */
  calculateAllScores(): ProviderTrustScore[] {
    const providerIds = Array.from(this.providerNames.keys());
    const scores: ProviderTrustScore[] = [];

    for (const providerId of providerIds) {
      try {
        const score = this.calculateProviderScore(providerId);
        scores.push(score);
      } catch (error) {
        logger.error(`Failed to calculate trust score for ${providerId}`, {
          error: error instanceof Error ? error.message : String(error),
        });
      }
    }

    // Sort by score descending
    scores.sort((a, b) => b.overallScore - a.overallScore);

    // Evaluate competitive badges (top performers)
    this.evaluateCompetitiveBadges(scores);

    logger.info('Trust scores calculated for all providers', {
      count: scores.length,
      topProvider: scores[0]?.providerId,
      topScore: scores[0]?.overallScore,
    });

    return scores;
  }

  /**
   * Get ranking of all providers by trust score
   */
  getProviderRanking(): ProviderTrustScore[] {
    if (!this.dbSink) {
      return [];
    }

    // Get cached scores from DB
    const cachedScores = this.dbSink.getAllLatestTrustScores();

    if (cachedScores.length === 0) {
      // Calculate fresh scores if no cache
      return this.calculateAllScores();
    }

    // Convert to ProviderTrustScore format
    return cachedScores.map(record => {
      const badges = this.dbSink?.getProviderBadges(record.providerId) ?? [];
      const warnings = this.dbSink?.getActiveWarnings(record.providerId) ?? [];

      let breakdown;
      try {
        breakdown = record.factorsJson ? JSON.parse(record.factorsJson) : null;
      } catch {
        breakdown = null;
      }

      return {
        providerId: record.providerId,
        providerName: this.providerNames.get(record.providerId) ?? record.providerId,
        overallScore: record.overallScore,
        tier: this.getTier(record.overallScore),
        breakdown: breakdown || {
          priceAccuracy: { score: record.priceAccuracyScore, details: '' },
          uptime: { score: record.uptimeScore, details: '' },
          reviews: { score: record.reviewScore, details: '' },
          freshness: { score: record.freshnessScore, details: '' },
        },
        badges,
        warnings,
        trend: 'stable' as const,
        lastUpdated: new Date(record.calculatedAt),
      };
    });
  }

  /**
   * Get trust score for a specific provider
   */
  getProviderScore(providerId: string): ProviderTrustScore | null {
    if (!this.dbSink) {
      return null;
    }

    const cached = this.dbSink.getLatestTrustScore(providerId);
    if (!cached) {
      // Calculate fresh if not cached
      return this.calculateProviderScore(providerId);
    }

    const badges = this.dbSink.getProviderBadges(providerId);
    const warnings = this.dbSink.getActiveWarnings(providerId);

    let breakdown;
    try {
      breakdown = cached.factorsJson ? JSON.parse(cached.factorsJson) : null;
    } catch {
      breakdown = null;
    }

    return {
      providerId: cached.providerId,
      providerName: this.providerNames.get(cached.providerId) ?? cached.providerId,
      overallScore: cached.overallScore,
      tier: this.getTier(cached.overallScore),
      breakdown: breakdown || {
        priceAccuracy: { score: cached.priceAccuracyScore, details: '' },
        uptime: { score: cached.uptimeScore, details: '' },
        reviews: { score: cached.reviewScore, details: '' },
        freshness: { score: cached.freshnessScore, details: '' },
      },
      badges,
      warnings,
      trend: 'stable',
      lastUpdated: new Date(cached.calculatedAt),
    };
  }

  /**
   * Get summary statistics
   */
  getSummary(): TrustScoreSummary {
    const providers = this.getProviderRanking();
    const avgScore = providers.length > 0
      ? providers.reduce((sum, p) => sum + p.overallScore, 0) / providers.length
      : 0;

    return {
      providers,
      totalProviders: providers.length,
      avgScore: Math.round(avgScore * 10) / 10,
      lastCalculated: new Date(),
    };
  }

  /**
   * Create a warning for a provider
   */
  createWarning(
    providerId: string,
    type: string,
    severity: 'low' | 'medium' | 'high' | 'critical',
    message: string,
    messageFa: string,
    dedupeKey?: string
  ): void {
    if (!this.dbSink) return;

    // Deterministic id per (provider, type, subject) so a warning that keeps
    // firing every crawl updates its row instead of colliding on the primary
    // key (multiple products can trip in the same millisecond).
    const idSuffix = dedupeKey ? `${type}_${dedupeKey}` : type;
    const warning: WarningRecord = {
      id: `warn_${providerId}_${idSuffix}`,
      providerId,
      warningType: type,
      severity,
      message,
      messageFa,
      active: true,
      createdAt: new Date().toISOString(),
    };

    this.dbSink.createWarning(warning);
    logger.warn('Provider warning created', { providerId, type, severity });
  }

  /**
   * Get all active warnings
   */
  getActiveWarnings(): WarningRecord[] {
    return this.dbSink?.getActiveWarnings() ?? [];
  }

  /**
   * Seed dummy data for testing/demo purposes
   */
  seedDummyData(): void {
    if (!this.dbSink) {
      logger.warn('Cannot seed dummy data: dbSink not initialized');
      return;
    }

    logger.info('Seeding dummy trust data...');

    const now = new Date().toISOString();
    const providerIds = Array.from(this.providerNames.keys());

    // Dummy score data for each provider
    const dummyScores: Record<string, { accuracy: number; uptime: number; reviews: number; freshness: number; badges: string[] }> = {
      'taline': { accuracy: 92, uptime: 99, reviews: 88, freshness: 95, badges: ['best_accuracy', 'reliable', 'fast_updates'] },
      'technogold': { accuracy: 88, uptime: 97, reviews: 82, freshness: 90, badges: ['verified', 'fast_updates'] },
      'digigold': { accuracy: 85, uptime: 95, reviews: 75, freshness: 88, badges: ['verified'] },
      'miligold': { accuracy: 78, uptime: 92, reviews: 80, freshness: 85, badges: ['high_rated'] },
      'talasea': { accuracy: 82, uptime: 94, reviews: 70, freshness: 82, badges: [] },
      'melligold': { accuracy: 75, uptime: 90, reviews: 65, freshness: 80, badges: [] },
      'tgju': { accuracy: 95, uptime: 99, reviews: 90, freshness: 98, badges: ['best_accuracy', 'reliable', 'high_rated'] },
      'bonbast': { accuracy: 80, uptime: 88, reviews: 72, freshness: 75, badges: [] },
      'alanchand': { accuracy: 76, uptime: 85, reviews: 68, freshness: 78, badges: [] },
      'goldika': { accuracy: 70, uptime: 82, reviews: 60, freshness: 70, badges: [] },
      'daric': { accuracy: 83, uptime: 91, reviews: 78, freshness: 85, badges: ['best_spread'] },
      'goldis': { accuracy: 79, uptime: 89, reviews: 74, freshness: 82, badges: [] },
    };

    // Create trust scores for all providers
    for (const providerId of providerIds) {
      const scores = dummyScores[providerId] || {
        accuracy: 50 + Math.random() * 40,
        uptime: 70 + Math.random() * 25,
        reviews: 50 + Math.random() * 40,
        freshness: 60 + Math.random() * 35,
        badges: [],
      };

      const overallScore =
        (scores.accuracy * TRUST_WEIGHTS.priceAccuracy) +
        (scores.uptime * TRUST_WEIGHTS.uptime) +
        (scores.reviews * TRUST_WEIGHTS.reviews) +
        (scores.freshness * TRUST_WEIGHTS.freshness);

      const breakdown = {
        priceAccuracy: { score: scores.accuracy, details: `${(10 - scores.accuracy / 10).toFixed(1)}% avg deviation` },
        uptime: { score: scores.uptime, details: `${scores.uptime.toFixed(1)}% uptime` },
        reviews: { score: scores.reviews, details: `${(1 + scores.reviews / 25).toFixed(1)}/5 rating` },
        freshness: { score: scores.freshness, details: 'Updated recently' },
      };

      // Save trust score
      const scoreRecord: TrustScoreRecord = {
        id: `trust_${providerId}_seed`,
        providerId,
        overallScore: Math.round(overallScore * 10) / 10,
        priceAccuracyScore: Math.round(scores.accuracy),
        uptimeScore: Math.round(scores.uptime),
        reviewScore: Math.round(scores.reviews),
        freshnessScore: Math.round(scores.freshness),
        calculatedAt: now,
        factorsJson: JSON.stringify(breakdown),
      };
      this.dbSink.saveTrustScore(scoreRecord);

      // Save badges
      for (const badgeType of scores.badges) {
        if (BADGE_DEFINITIONS[badgeType]) {
          this.dbSink.saveBadge({
            id: `badge_${providerId}_${badgeType}`,
            providerId,
            ...BADGE_DEFINITIONS[badgeType],
            awardedAt: now,
            autoGenerated: true,
          });
        }
      }

      // Update freshness tracking
      this.lastFetchTimes.set(providerId, new Date());
    }

    // Add some dummy reviews
    const reviewProviders = ['taline', 'technogold', 'tgju', 'digigold', 'miligold'];
    const reviewTitles = [
      { title: 'عالی', titleEn: 'Excellent' },
      { title: 'خوب بود', titleEn: 'Good' },
      { title: 'قیمت مناسب', titleEn: 'Fair price' },
      { title: 'سرعت خوب', titleEn: 'Fast service' },
      { title: 'پیشنهاد میکنم', titleEn: 'Recommended' },
    ];
    const reviewContents = [
      'قیمت‌ها دقیق و به‌روز هستند. خیلی راضی بودم از خرید.',
      'سرعت به‌روزرسانی قیمت‌ها خوب است. پشتیبانی هم پاسخگو بودند.',
      'تجربه خوبی داشتم. قیمت‌ها منصفانه بود.',
      'اختلاف قیمت خرید و فروش کم است. توصیه می‌کنم.',
      'از چند ماه پیش از این سایت استفاده می‌کنم. راضی هستم.',
    ];

    let reviewIndex = 0;
    for (const providerId of reviewProviders) {
      const numReviews = 2 + Math.floor(Math.random() * 4); // 2-5 reviews
      for (let i = 0; i < numReviews; i++) {
        const rating = 3 + Math.floor(Math.random() * 3); // 3-5 stars
        const titleData = reviewTitles[reviewIndex % reviewTitles.length];
        const content = reviewContents[reviewIndex % reviewContents.length];

        this.dbSink.saveReview({
          id: `rev_seed_${providerId}_${i}`,
          providerId,
          userFingerprint: `seed_user_${reviewIndex}`,
          rating,
          title: titleData.title,
          content,
          transactionVerified: Math.random() > 0.5,
          helpfulCount: Math.floor(Math.random() * 10),
          reportCount: 0,
          status: 'active',
          createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        });
        reviewIndex++;
      }
    }

    // Add a couple of warnings
    this.dbSink.createWarning({
      id: 'warn_seed_goldika',
      providerId: 'goldika',
      warningType: 'high_deviation',
      severity: 'medium',
      message: 'Price deviation above 3% from market average',
      messageFa: 'اختلاف قیمت بیش از ۳٪ با میانگین بازار',
      active: true,
      createdAt: now,
    });

    this.dbSink.createWarning({
      id: 'warn_seed_bonbast',
      providerId: 'bonbast',
      warningType: 'slow_updates',
      severity: 'low',
      message: 'Slower than average price updates',
      messageFa: 'به‌روزرسانی قیمت کندتر از میانگین',
      active: true,
      createdAt: now,
    });

    logger.info('Dummy trust data seeded successfully', {
      providers: providerIds.length,
      reviews: reviewIndex,
    });
  }
}

// Singleton instance
let trustScoreService: TrustScoreService | null = null;

export function getTrustScoreService(): TrustScoreService {
  if (!trustScoreService) {
    trustScoreService = new TrustScoreService();
  }
  return trustScoreService;
}
